version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive

formatters:
  enable:
    - gofmt
    - goimports

formatters-settings:
  goimports:
    local-prefixes:
      - github.com/outfitte/outfitte

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
