blank_issues_enabled: false
contact_links:
  - name: Outfitte Discussion
    url: https://github.com/Outfitte/Outfitte/discussions
    about: Ask questions and discuss ideas with the Outfitte community.
