name: OpenAPI Lint

on:
  push:
    paths:
      - docs/openapi.yaml
      - .spectral.yaml
  pull_request:
    paths:
      - docs/openapi.yaml
      - .spectral.yaml

jobs:
  spectral:
    runs-on: builder
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - uses: stoplightio/spectral-action@v0.8.13
        with:
          file_glob: docs/openapi.yaml
